<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TypeReunion;

class TypeReunionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $typesReunions = [
            [
                'nom' => 'Culte du Dimanche Matin',
                'code' => 'CULTE_DIM_MATIN',
                'description' => 'Culte principal du dimanche matin avec prédication, louange et communion fraternelle.',
                'categorie' => 'spirituel',
                'niveau_acces' => 'public',
                'frequence_type' => 'hebdomadaire',
                'duree_standard' => '02:30:00',
                'duree_min' => '02:00:00',
                'duree_max' => '03:00:00',
                'inclut_louange' => true,
                'inclut_message' => true,
                'inclut_priere' => true,
                'inclut_communion' => true,
                'permet_temoignages' => true,
                'collecte_offrandes' => true,
                'permet_enregistrement' => true,
                'permet_diffusion_live' => true,
                'necessite_promotion' => true,
                'afficher_calendrier_public' => true,
                'afficher_site_web' => true,
                'icone' => 'fas fa-church',
                'couleur' => '#3498db',
                'ordre_affichage' => 1,
                'priorite' => 10,
            ],
            [
                'nom' => 'Culte du Dimanche Soir',
                'code' => 'CULTE_DIM_SOIR',
                'description' => 'Culte du soir plus intime, propice à la méditation et aux témoignages.',
                'categorie' => 'spirituel',
                'niveau_acces' => 'public',
                'frequence_type' => 'hebdomadaire',
                'duree_standard' => '02:00:00',
                'inclut_louange' => true,
                'inclut_message' => true,
                'inclut_priere' => true,
                'permet_temoignages' => true,
                'collecte_offrandes' => true,
                'permet_enregistrement' => true,
                'afficher_calendrier_public' => true,
                'afficher_site_web' => true,
                'icone' => 'fas fa-moon',
                'couleur' => '#9b59b6',
                'ordre_affichage' => 2,
                'priorite' => 8,
            ],
            [
                'nom' => 'École du Dimanche',
                'code' => 'ECOLE_DIMANCHE',
                'description' => 'Classes d\'enseignement biblique pour tous les âges : enfants, jeunes et adultes.',
                'categorie' => 'spirituel',
                'niveau_acces' => 'public',
                'frequence_type' => 'hebdomadaire',
                'duree_standard' => '01:30:00',
                'inclut_priere' => true,
                'permet_enfants' => true,
                'permet_enregistrement' => false,
                'necessite_preparation' => true,
                'afficher_calendrier_public' => true,
                'afficher_site_web' => true,
                'icone' => 'fas fa-graduation-cap',
                'couleur' => '#f39c12',
                'ordre_affichage' => 3,
                'priorite' => 9,
            ],
            [
                'nom' => 'Réunion de Prière',
                'code' => 'REUNION_PRIERE',
                'description' => 'Temps de prière collective, intercession et communion spirituelle.',
                'categorie' => 'spirituel',
                'niveau_acces' => 'membres',
                'frequence_type' => 'hebdomadaire',
                'duree_standard' => '01:30:00',
                'inclut_priere' => true,
                'permet_temoignages' => true,
                'permet_enregistrement' => false,
                'afficher_calendrier_public' => true,
                'icone' => 'fas fa-praying-hands',
                'couleur' => '#27ae60',
                'ordre_affichage' => 4,
                'priorite' => 7,
            ],
            [
                'nom' => 'Réunion de Jeunes',
                'code' => 'REUNION_JEUNES',
                'description' => 'Rencontre hebdomadaire des jeunes avec animations, études bibliques et fellowship.',
                'categorie' => 'spirituel',
                'niveau_acces' => 'public',
                'frequence_type' => 'hebdomadaire',
                'duree_standard' => '02:30:00',
                'inclut_louange' => true,
                'inclut_message' => true,
                'inclut_priere' => true,
                'permet_temoignages' => true,
                'permet_enfants' => false,
                'age_minimum' => 13,
                'permet_enregistrement' => true,
                'afficher_calendrier_public' => true,
                'afficher_site_web' => true,
                'icone' => 'fas fa-users',
                'couleur' => '#e74c3c',
                'ordre_affichage' => 5,
                'priorite' => 6,
            ],
            [
                'nom' => 'Conseil d\'Église',
                'code' => 'CONSEIL_EGLISE',
                'description' => 'Réunion mensuelle du conseil pour les décisions importantes de l\'église.',
                'categorie' => 'administratif',
                'niveau_acces' => 'leadership',
                'frequence_type' => 'mensuel',
                'duree_standard' => '02:00:00',
                'inclut_priere' => true,
                'necessite_preparation' => true,
                'necessite_rapport' => true,
                'permet_enregistrement' => false,
                'afficher_calendrier_public' => false,
                'icone' => 'fas fa-users-cog',
                'couleur' => '#34495e',
                'ordre_affichage' => 6,
                'priorite' => 8,
            ],
            [
                'nom' => 'Formation Biblique',
                'code' => 'FORMATION_BIBLIQUE',
                'description' => 'Sessions de formation approfondie sur les Écritures et la doctrine méthodiste.',
                'categorie' => 'spirituel',
                'niveau_acces' => 'membres',
                'frequence_type' => 'irregulier',
                'duree_standard' => '03:00:00',
                'inclut_priere' => true,
                'necessite_preparation' => true,
                'necessite_inscription' => true,
                'permet_enregistrement' => true,
                'afficher_calendrier_public' => true,
                'afficher_site_web' => true,
                'icone' => 'fas fa-book-open',
                'couleur' => '#16a085',
                'ordre_affichage' => 7,
                'priorite' => 5,
            ],
            [
                'nom' => 'Ministère des Femmes',
                'code' => 'MINISTERE_FEMMES',
                'description' => 'Rencontres spéciales pour les femmes de l\'église avec enseignements et fellowship.',
                'categorie' => 'spirituel',
                'niveau_acces' => 'membres',
                'frequence_type' => 'mensuel',
                'duree_standard' => '02:00:00',
                'inclut_louange' => true,
                'inclut_message' => true,
                'inclut_priere' => true,
                'permet_temoignages' => true,
                'afficher_calendrier_public' => true,
                'afficher_site_web' => true,
                'icone' => 'fas fa-female',
                'couleur' => '#e91e63',
                'ordre_affichage' => 8,
                'priorite' => 4,
            ],
            [
                'nom' => 'Réunion d\'Évangélisation',
                'code' => 'EVANGELISATION',
                'description' => 'Réunions spéciales d\'évangélisation pour atteindre les non-croyants.',
                'categorie' => 'spirituel',
                'niveau_acces' => 'public',
                'frequence_type' => 'irregulier',
                'duree_standard' => '02:30:00',
                'inclut_louange' => true,
                'inclut_message' => true,
                'inclut_priere' => true,
                'permet_temoignages' => true,
                'compte_conversions' => true,
                'compte_nouveaux' => true,
                'permet_diffusion_live' => true,
                'necessite_promotion' => true,
                'afficher_calendrier_public' => true,
                'afficher_site_web' => true,
                'icone' => 'fas fa-bullhorn',
                'couleur' => '#ff9800',
                'ordre_affichage' => 9,
                'priorite' => 7,
            ],
            [
                'nom' => 'Assemblée Générale',
                'code' => 'ASSEMBLEE_GENERALE',
                'description' => 'Assemblée générale annuelle pour les rapports et décisions importantes.',
                'categorie' => 'administratif',
                'niveau_acces' => 'membres',
                'frequence_type' => 'annuel',
                'duree_standard' => '04:00:00',
                'inclut_priere' => true,
                'necessite_preparation' => true,
                'necessite_rapport' => true,
                'necessite_promotion' => true,
                'afficher_calendrier_public' => true,
                'icone' => 'fas fa-gavel',
                'couleur' => '#795548',
                'ordre_affichage' => 10,
                'priorite' => 9,
            ],
        ];

        foreach ($typesReunions as $typeData) {
            TypeReunion::updateOrCreate(
                ['code' => $typeData['code']],
                $typeData
            );
        }

        $this->command->info('✅ Types de réunions créés avec succès !');
    }
}
